version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:3000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    volumes:
      - app_runtime:/app/runtime
      - app_templates:/app/templates
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  app_runtime:
  app_templates:
